#!/usr/bin/env python3
"""Generate a prefix-parameterised copy of the fridge-stats package.

The stock package hard-codes ``fridge_`` entity ids, so a second appliance
(freezer, garage fridge, ...) needs its own copy under another prefix. Entity
ids in the package arise two different ways — helper ids from the YAML object
keys, sensor ids from the *slugified display name* (which is why the German
variant has ``sensor.kuhlschrank_*``) — so a naive search-and-replace can leave
dangling references. This generator rewrites all id families consistently and
then PROVES the result: it parses the output, predicts every entity id the
package will create, and asserts that every internal reference resolves.

Usage:
  python3 make_package.py --prefix freezer                     # EN, to stdout
  python3 make_package.py --prefix gefrierschrank --lang de \
      --out packages/gefrierschrank_stats.yaml

The display name shown in the UI is derived from the prefix (``freezer`` ->
"Freezer", ``garage_fridge`` -> "Garage fridge"); ``--display`` overrides it,
but its slug must equal the prefix — that invariant is what keeps the
name-derived sensor ids aligned with the rewritten references. Rename display
names later in the UI if you like; registry renames keep entity ids.

After writing, the blueprint-input mapping for the new helper set is printed —
paste those into a new automation created from the fridge_door_monitor
blueprint. A Home Assistant restart is required (packages load at startup).
"""
import argparse
import re
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required for output validation: pip install pyyaml")

# tokens of the stock package, per language
LANG = {
    "en": {"suffix": "", "display_token": "Fridge", "slug_families": ["fridge_"]},
    "de": {"suffix": ".de", "display_token": "Kühlschrank",
           "slug_families": ["fridge_", "kuhlschrank_"]},
}

HELPER_DOMAINS = ["input_boolean", "input_number", "input_datetime", "input_text", "counter"]

# blueprint state-helper inputs -> stock default entity (suffix after the prefix)
BLUEPRINT_MAP = [
    ("helper_door_open", "input_boolean", "door_open"),
    ("helper_t0", "input_number", "t0"),
    ("helper_troom0", "input_number", "troom0"),
    ("helper_peak", "input_number", "peak"),
    ("helper_tau", "input_number", "tau"),
    ("helper_opened_at", "input_datetime", "opened_at"),
    ("helper_last_duration", "input_number", "last_open_duration"),
    ("helper_last_class", "input_text", "last_event_class"),
    ("counter_openings", "counter", "openings_total"),
    ("helper_open_seconds_total", "input_number", "open_seconds_total"),
    # fridge_humidity_monitor only (door monitor ignores it); its other two
    # helper inputs (helper_door_open, helper_last_class) are listed above
    ("counter_short_grabs", "counter", "short_grabs_total"),
]

TRANSLIT = str.maketrans({"ä": "a", "ö": "o", "ü": "u", "ß": "ss",
                          "Ä": "a", "Ö": "o", "Ü": "u"})


def slugify(name):
    """Home Assistant style: lowercase, transliterate umlauts, non-alnum -> _."""
    s = name.translate(TRANSLIT).lower()
    s = re.sub(r"[^a-z0-9]+", "_", s)
    return s.strip("_")


def transform(text, lang, prefix, display):
    cfg = LANG[lang]
    for fam in cfg["slug_families"]:
        text = text.replace(fam, f"{prefix}_")
    # display token as a whole word (name strings and comments alike)
    text = re.sub(rf"\b{cfg['display_token']}\b", display, text)
    header = (f"# GENERATED by make_package.py from fridge_stats{cfg['suffix']}.yaml "
              f"— prefix '{prefix}', display '{display}'.\n"
              f"# Regenerate instead of hand-editing; upstream fixes land in the stock package.\n")
    return header + text


def predicted_ids(doc):
    """Every entity id this package will create."""
    ids = set()
    for domain in HELPER_DOMAINS:
        for key in (doc.get(domain) or {}):
            ids.add(f"{domain}.{key}")
    for block in (doc.get("template") or []):
        for sensor in (block.get("sensor") or []):
            ids.add(f"sensor.{slugify(sensor['name'])}")
    for entry in (doc.get("sensor") or []):
        if "name" in entry:
            ids.add(f"sensor.{slugify(entry['name'])}")
    for key, meter in (doc.get("utility_meter") or {}).items():
        ids.add(f"sensor.{slugify(meter.get('name', key))}")
    return ids


REF_RE = re.compile(
    r"\b(input_boolean|input_number|input_datetime|input_text|counter|sensor)"
    r"\.([a-z0-9_]+)")


def validate(text, lang, prefix):
    doc = yaml.safe_load(text)
    defined = predicted_ids(doc)

    # scan references on non-comment lines only (the EN header cites the DE ids)
    code_lines = [ln for ln in text.splitlines() if not ln.lstrip().startswith("#")]
    problems = []
    for ln in code_lines:
        for m in REF_RE.finditer(ln):
            ref = f"{m.group(1)}.{m.group(2)}"
            if ref not in defined:
                problems.append(f"dangling reference: {ref}")
    # every entity the package creates must carry the prefix — this catches any
    # missed rewrite (a leftover fridge_* key) and, unlike a substring scan,
    # stays correct for prefixes that themselves contain a stock family
    # (e.g. 'garage_fridge')
    for eid in defined:
        obj = eid.split(".", 1)[1]
        if not obj.startswith(f"{prefix}_"):
            problems.append(f"entity without prefix '{prefix}_': {eid}")
    if problems:
        raise SystemExit("VALIDATION FAILED:\n  " + "\n  ".join(sorted(set(problems))))
    return len(defined)


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--prefix", required=True,
                    help="entity-id prefix for the new appliance, e.g. 'freezer'")
    ap.add_argument("--lang", choices=("en", "de"), default="en")
    ap.add_argument("--display", default=None,
                    help="display-name token (default: derived from prefix); "
                         "its slug must equal the prefix")
    ap.add_argument("--out", default=None, help="output file (default: stdout)")
    ap.add_argument("--source-dir", default=str(Path(__file__).parent / "package"))
    args = ap.parse_args()

    # strict, no silent normalization: deploy.sh uses the prefix verbatim for its
    # stock-vs-generated branch, the output filename and the tau-helper hint — a
    # value normalized only here would diverge from all three (e.g. '_fridge_'
    # would dodge deploy.sh's stock branch yet generate stock fridge_* entities,
    # duplicating every helper definition)
    prefix = args.prefix
    if not re.fullmatch(r"[a-z][a-z0-9]*(?:_[a-z0-9]+)*", prefix):
        sys.exit(f"invalid prefix {args.prefix!r}: lowercase ascii letters/digits with "
                 f"single inner underscores (no leading/trailing '_', no uppercase) — "
                 f"the value is used verbatim in entity ids and by deploy.sh")
    display = args.display or prefix.replace("_", " ").capitalize()
    if slugify(display) != prefix:
        sys.exit(f"display {display!r} slugs to '{slugify(display)}', which must equal "
                 f"the prefix '{prefix}' — otherwise the name-derived sensor ids "
                 f"diverge from the rewritten references")

    src = Path(args.source_dir) / f"fridge_stats{LANG[args.lang]['suffix']}.yaml"
    out_text = transform(src.read_text(encoding="utf-8"), args.lang, prefix, display)
    count = validate(out_text, args.lang, prefix)

    if args.out:
        Path(args.out).write_text(out_text, encoding="utf-8")
        print(f"wrote {args.out} ({count} entities, validated)")
    else:
        sys.stdout.write(out_text)

    print(f"\nBlueprint inputs for the '{display}' automations "
          f"(fridge_door_monitor — and fridge_humidity_monitor if used; "
          f"State helpers section):", file=sys.stderr)
    for inp, domain, suffix in BLUEPRINT_MAP:
        print(f"  {inp:26} -> {domain}.{prefix}_{suffix}", file=sys.stderr)
    print("Remember: Home Assistant restart required (packages load at startup).",
          file=sys.stderr)


if __name__ == "__main__":
    main()
